---
title: DCDW
timezone: America/New_York
collections:
  dcdw-committee-members:
    title: DCDW-Committee-Members
    output: true
  dcdw-creative-team:
    title: DCDW-Creative-Team
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: singles/event
    single-event-header-image: 
    event-date: 
    event-venue-name: 
    event-venue-directions: 
    is-featured-on-home-page: 
    is-even-on-home-page: 
    is-even-on-events-page: 
    speakers:
    - speaker-headshot-image: 
      speaker-name: 
      speaker-title: 
      speaker-bio: 
- scope:
    path: ''
    type: sponsors
  values:
    sponsor-image: 
    is-even-on-home-page: 
    is-first-tier: 
    is-second-tier: 
    is-third-tier: 
- scope:
    path: ''
    type: dcdw-committee-members
  values:
    committee-member-headshot-image: 
    committee-member-name: 
    committee-member-title: 
    committee-member-email: 
- scope:
    path: ''
    type: dcdw-creative-team
  values:
    creative-team-member-headshot-image: 
    creative-team-member-name: 
    creative-team-member-title: 
    creative-team-member-portfolio: 
- scope:
    path: ''
    type: speakers
  values:
    speaker-headshot-image: 
    speaker-name: 
    speaker-title: 
    speaker-bio: 
favicon-image: 
google-analytics: "<script> \n(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n\n
  \ ga('create', 'UA-84499644-1', 'auto');\n  ga('send', 'pageview');\n</script>"
desktop-logo-image: "/uploads/dcdw-logo-desktop.svg"
mobile-logo-image: "/uploads/dcdw-logo-mobile.svg"
contact-email: dcdw@aigadc.org
copyright: "© AIGA DC | 2016 All Rights Reserved."
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
sass:
  sass_dir: _sass
  style: compressed
