---
title: DC Design Week 2017
timezone: America/New_York
collections:
  dcdw-committee-members:
    title: DCDW-Committee-Members
    output: true
  dcdw-creative-team:
    title: DCDW-Creative-Team
    output: true
  events:
    title: Events
    output: true
  jobs:
    title: Jobs
    output: true
  posts:
    title: Posts
    output: true
  social-media:
    title: Social-Media
    output: true
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: singles/event
    title: 
    description: 
    image: 
    og-image: 
    is-sold-out: 
    is-featured-on-home-page: 
    is-featured-on-events-page: 
    is-kickoff-friday: 
    is-sunday: 
    is-monday: 
    is-tuesday: 
    is-wednesday: 
    is-thursday: 
    is-friday: 
    is-saturday: 
    single-event-header-image: 
    has-video: 
    video-embed: 
    event-date: 
    event-venue-name: 
    event-venue-directions: 
    event-venue-address: 
    doors-open: 
    event-start: 
    is-even-on-home-page: 
    is-even-on-events-page: 
    has-speakers: 
    presenter-section-header: 
    speakers:
    - speaker-headshot-image: 
      speaker-link: 
      speaker-name: 
      speaker-title: 
      speaker-bio-text: 
    left-button-link: 
    left-button-text: 
    has-right-button: 
    right-button-link: 
    right-button-text: 
- scope:
    path: ''
    type: sponsors
  values:
    sponsor-url: 
    is-featured-on-home-page: 
    is-featured-on-shops-galleries-page: 
    sponsor-image: 
    is-even-on-home-page: 
    is-first-tier: 
    is-second-tier: 
    is-third-tier: 
- scope:
    path: ''
    type: dcdw-committee-members
  values:
    committee-member-headshot-image: 
    committee-member-name: 
    committee-member-title: 
    committee-member-email: 
- scope:
    path: ''
    type: dcdw-creative-team
  values:
    creative-team-member-headshot-image: 
    creative-team-member-name: 
    creative-team-member-title: 
    creative-team-member-portfolio: 
- scope:
    path: ''
    type: social-media
  values:
    social-media-link: 
    social-media-icon: 
- scope:
    path: ''
    type: jobs
  values:
    position: 
    title: 
    jobs:
    - 
    - 
    commitment: 
    avatar: "/uploads/team_avatar.jpg"
    name: "——?——"
    layout: pages/job-desc
    exec: false
    permalink: "/committee/:title"
repository: AIGAdc/DCDW
favicon-image: "/uploads/favicon-31b9a4.ico"
google-analytics: "<script> \n(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n\n
  \ ga('create', 'UA-84499644-1', 'auto');\n  ga('send', 'pageview');\n</script>"
desktop-logo-image: "/uploads/dcdw-logo-desktop.svg"
mobile-logo-image: "/uploads/dcdw-logo-mobile.svg"
footer-contact-email: dcdw@aigadc.org
footer-social-links:
- facebook: facebook-square
- twitter: twitter-square
- instagram: instagram
- flickr: flickr
footer-copyright: "© AIGA DC | 2017  All Rights Reserved."
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
gems:
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
url: http://www.dcdesignweek.org
description: DC Design Week is a celebration of creatives, thinkers, and makers in
  the DC metro area. Its a week packed with amazing speakers, events, and meetups.
  Join us!
og-image: "/uploads/OG_featuredimage-revised.jpg"
twitter:
  username: aigadc
facebook:
  publisher: https://www.facebook.com/aigaDC/
logo: "/uploads/dcdw-logo-desktop.svg"
