---
title: DCDW
timezone: America/New_York
collections:
  dcdw-committee-members:
    title: DCDW-Committee-Members
    output: true
  dcdw-creative-team:
    title: DCDW-Creative-Team
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  social-media:
    title: Social-Media
    output: true
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: singles/event
    is-featured-on-home-page: 
    is-featured-on-events-page: 
    is-kickoff-friday: 
    is-sunday: 
    is-monday: 
    is-tuesday: 
    is-wednesday: 
    is-thursday: 
    is-friday: 
    is-saturday: 
    single-event-header-image: 
    event-date: 
    event-venue-name: 
    event-venue-directions: 
    is-even-on-home-page: 
    is-even-on-events-page: 
    has-speakers: 
    presenter-section-header: 
    speakers:
    - speaker-headshot-image: 
      speaker-link: 
      speaker-name: 
      speaker-title: 
      speaker-bio: 
    left-button-link: 
    left-button-text: 
    right-button-link: 
    right-button-text: 
- scope:
    path: ''
    type: sponsors
  values:
    is-featured-on-home-page: 
    sponsor-image: 
    is-even-on-home-page: 
    is-first-tier: 
    is-second-tier: 
    is-third-tier: 
- scope:
    path: ''
    type: dcdw-committee-members
  values:
    committee-member-headshot-image: 
    committee-member-name: 
    committee-member-title: 
    committee-member-email: 
- scope:
    path: ''
    type: dcdw-creative-team
  values:
    creative-team-member-headshot-image: 
    creative-team-member-name: 
    creative-team-member-title: 
    creative-team-member-portfolio: 
- scope:
    path: ''
    type: social-media
  values:
    social-media-link: 
    social-media-icon: 
favicon-image: "/uploads/favicon-31b9a4.ico"
meta-description: DC Design Week is a celebration of creatives, thinkers, and makers
  in the DC metro area. Its a week packed with amazing speakers, events, and meetups.
  Join  us!
meta-og-url: http://www.dcdesignweek.org
meta-og-description: DC Design Week is a celebration of creatives, thinkers, and makers
  in the DC metro area. Its a week packed with amazing speakers, events, and meetups.
  Join  us!
meta-og-title: DC Design Week
meta-og-image: "/uploads/2ff78010-8012-11e6-9065-d784d2d1f218.jpg"
google-analytics: "<script> \n(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n\n
  \ ga('create', 'UA-84499644-1', 'auto');\n  ga('send', 'pageview');\n</script>"
desktop-logo-image: "/uploads/dcdw-logo-desktop.svg"
mobile-logo-image: "/uploads/dcdw-logo-mobile.svg"
footer-contact-email: dan@aigadc.org
footer-social-links:
- facebook: facebook-square
- twitter: twitter-square
- instagram: instagram
- flickr: flickr
footer-copyright: "© AIGA DC | 2016 All Rights Reserved."
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
sass:
  sass_dir: _sass
  style: compressed
